import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import { generateWebsiteCode } from '../lib/gpt3';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
const [instructions, setInstructions] = useState('');
const [generatedCode, setGeneratedCode] = useState('');

const handleSubmit = async (e) => {
  e.preventDefault();
  const code = await generateWebsiteCode(instructions);
  setGeneratedCode(code);
};
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-gray-100 min-h-screen">
          <div className="max-w-2xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h1 className="text-3xl font-extrabold text-gray-900 sm:text-4xl">
              Generate a Website with OpenAI
            </h1>
            <form onSubmit={handleSubmit} className="mt-8 sm:flex">
              <div className="w-full sm:max-w-md">
                <label htmlFor="instructions" className="sr-only">
                  Instructions
                </label>
                <textarea
                  id="instructions"
                  name="instructions"
                  value={instructions}
                  onChange={(e) => setInstructions(e.target.value)}
                  rows={5}
                  className="block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                  placeholder="Enter your instructions here..."
                />
              </div>
              <button
                type="submit"
                className="mt-3 w-full px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm"
              >
                Generate Website
              </button>
            </form>
            <div className="mt-8">
              <label htmlFor="generated-code" className="sr-only">
                Generated Code
              </label>
              <textarea
                id="generated-code"
                name="generated-code"
                value={generatedCode}
                readOnly
                rows={10}
                className="block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                placeholder="Generated code will appear here..."
              />
            </div>
          </div>
        </main>
      </>
    )
  }
